### ISSUE TITLE
Práctica 1_Reporte de app de Realidad Aumentada

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Anthony4523#2]
[Práctica 1_App con realidad aumentada.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Anthony4523/files/8103426/Practica.1_App.con.realidad.aumentada.pdf)

**Comment by IvanMc98** [comment]
EL reporte de la practica cuenta con todos los puntos de la rubrica, la explicación del proyecto es clara y objetiva.
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
